format_version: 2
pipelines:
  myx-pipeline:
    group: vue-todo
    materials:
      git-repo:
        git: https://github.com/myx4play/vue-gotham-todo
        branch: master
    stages:
      - zero-stage:
          approve:
            type: manual
          jobs:
            list:
              tasks:
                - exec:
                    command: ls

      - first-stage:
          approve: manual
            type: manual
          jobs:
            list:
              tasks:
                - exec:
                    command: ./gotham-todo/build.sh
                - exec:
                    command: ./gotham-todo/apply-infrastructure.sh

